### ISSUE TITLE
Performance: Generate XPaths ahead of time

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#1199]
Some of the XPath generation code uses `glue::glue()` with configuration-dependent (but not file-dependent) input.
Currently, on every `lint()` these XPaths are recomputed, amounting to quite a few ms spent on `glue::glue()` e.g. in the test suite.

It is much more efficient to compute the XPath in the linter factory instead, whenever that is possible.

**Comment by MichaelChirico** [comment]
#1222 had me thinking:

`namespace_linter` is a case where there's a lot of logic we may be stuck keeping inside the linter, because it runs `.packages()`, `getNamespace()`, etc. which in principle could differ between (lintr config) compile time & run time.

Where that's not the case, I think it's fine to move logic into the factory by default (for consistency), even when glue() is not involved.
