### ISSUE TITLE
simpleError in match.arg(semicolon, several.ok = TRUE): 'arg' must be NULL or a character vector

### ISSUE THREAD

**Issue by pascalgulikers** [r-lib/lintr#1426]
Hi, I get this error on every lintr::lint_package() call. There's not much more information except that it worked in 2.0.1 but broke in 3.0.0

**Comment by pascalgulikers** [comment]
Found it, I guess:

linters: with_defaults(absolute_path_linter, implicit_integer_linter, line_length_linter(120), nonportable_path_linter, object_usage_linter=NULL, semicolon_terminator_linter, T_and_F_symbol_linter, todo_comment_linter, undesirable_function_linter, undesirable_operator_linter, unneeded_concatenation_linter)
exclude: "\\$[A-Z]"

semicolon_terminator_linter is deprecated and should be semicolon_linter..

**Comment by AshesITR** [comment]
This is an unfortunate collision of two things:

* `semicolon_terminator_linter()` already had a configuration option, so it cannot be passed by name in 2.0.1
* The "smell test" for `semicolon_terminator_linter` succeeds, because that is also a function of one argument, as a linter should be.

Indeed, the first step in your refactoring should be to add `()` to all linters in your config - even those without options.
That would give you two warnings:

```r
lintr::with_defaults(lintr::semicolon_terminator_linter())
#> Warning: Function with_defaults was deprecated in lintr version 3.0.0. Use linters_with_defaults instead.
#> Warning: Linter semicolon_terminator_linter was deprecated in lintr version 3.0.0. Use semicolon_linter instead.
```
