### ISSUE TITLE
lintr hangs on openxlsx

### ISSUE THREAD

**Issue by JanMarvin** [r-lib/lintr#1443]
Hello,
in one of the many packages for which I use `lintr`, `lintr` started hanging after the last version 3.0. This can be reproduced both locally (R 4.2.1 on Mac and `lintr`s HEAD) and in the Github action.

`lintr::lint_package()` hangs on [`openxlsx`](https://github.com/ycphs/openxlsx). This can be seen with the latest CRAN release of `openxlsx` and also in the `development` branch. While the `openxlsx` code is known to be a mess, `lintr` did not hang before its release 3.0. Unfortunately there is not much else I can report, there is no verbose option that I am aware of. I tried to disable the linter mentioned in #1427 but that did not help. Let me know if you need anything else.

Thank you for the time you have invested in the development and maintenance of `lintr`!

**Comment by MichaelChirico** [comment]
Thanks for the report! I'm definitely reproducing strange slowness at [current HEAD on `openxlsx`](https://github.com/ycphs/openxlsx/tree/3ceeb84e5466bb6558bc01c7fbfc75b1a9503431).

To debug, I start with:

```r
trace(lintr::lint, at=1, quote(message(filename)))
lintr::lint_package()
```

this shows me what files are going slowly, and where it gets stuck.

[`R/wrappers.R`](https://github.com/ycphs/openxlsx/blob/3ceeb84e5466bb6558bc01c7fbfc75b1a9503431/R/wrappers.R) is quite slow -- perhaps not surprising as it clocks in at 4K lines.

But where it really gets stuck is [`vignettes/Intro.Rmd`](https://github.com/ycphs/openxlsx/blob/3ceeb84e5466bb6558bc01c7fbfc75b1a9503431/vignettes/Introduction.Rmd). This is strange because the file is not very large.

It looks like `get_source_expressions()` is choking on that file; investigating why.

**Comment by MichaelChirico** [comment]
OK, the issue is that there's a syntax error in the vignette. This is hidden because `eval=FALSE` in all the chunks. Maybe we should re-open #581?

It's not clear we're _supposed_ to lint in chunks where `eval=FALSE` in the first place. But also, we shouldn't get stuck in an infinite loop in edge cases like this.

**Comment by JanMarvin** [comment]
Thanks for the explanation and the successful bug hunt!
