### ISSUE TITLE
Lost braced in backport_linter docs

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#2236]
Seen in a run for #2213.
The Rd file for `backport_linter()` contains verbatim `{}`.

How do we want to style package names in general?

If `{pkg}` is our preferred style, we need to escape it in the roxygen so it renders as `\{pkg\}` to Rd. Otherwise, we should change the style.

**Comment by IndrajeetPatil** [comment]
@MichaelChirico I think this needs to be resolved for `3.1.1`. Otherwise, the package won't pass CRAN's incoming check.

I like formatting it as code (i.e. `` `{pkg}` ``) because then `{pkgdown}` generates a link to the package's pkgdown website: 

``` r
downlit:::autolink_curly("{lintr}")
#> [1] "<a href='https://github.com/r-lib/lintr'>lintr</a>"
```

<sup>Created on 2023-10-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
