### ISSUE TITLE
Rearrange `linter_level=` in our code.

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#2355]
I'm not a fan of this style, WDYT about rearranging instead:

```r
Linter(linter_level = "expression", function(source_expression) {
  ...
})
```

_Originally posted by @MichaelChirico in https://github.com/r-lib/lintr/pull/2352#discussion_r1405674392_

**Comment by IndrajeetPatil** [comment]
If we are open to making formatting changes for readability, I actually prefer the following style over inlining because it visually separates the function name from its argument in the function call:

```r
Linter(
  linter_level = "expression", 
  function(source_expression) {
  ...
  }
)
```

This way, I also don't need to parse the commas to separate where one parameter and its argument begins and ends, and the next one starts:

```r
Linter <- function(fun, name = linter_auto_name(), linter_level = c(NA_character_, "file", "expression")) { 
  ...
}
```


```r
Linter <- function(fun, 
                   name = linter_auto_name(), 
                   linter_level = c(NA_character_, "file", "expression")) { 
  ...
}
```
