### ISSUE TITLE
No visible global function definition for '%>%'

### ISSUE THREAD

**Issue by Aman9das** [r-lib/lintr#2522]
I'm writing a quarto document, and the usage of %>% pipe inside function is throwing an warning.
But outside function it is not throwing error. 

````
---
title: Probably a Fire Hazard - Star 2
author: Aman9das
---

```{r}
library(tidyverse)
```

```{r}
mt <- 0 %>% matrix(1000, 1000) # No error

switch_lights <- function(row, mt) {
  cmd <- row[1]
  x0 <- row[2] %>% as.integer() + 1 # Error
  x1 <- row[4] %>% as.integer() + 1 # Error
  y0 <- row[3] %>% as.integer() + 1 # Error
  y1 <- row[5] %>% as.integer() + 1 # Error

  if (cmd == "toggle") {
    mt[x0:x1, y0:y1] <- mt[x0:x1, y0:y1] + 2
  } else if (cmd == "on") {
    mt[x0:x1, y0:y1] <- mt[x0:x1, y0:y1] + 1
  } else if (cmd == "off") {
    mt[x0:x1, y0:y1] <- (mt[x0:x1, y0:y1] - 1) %>% pmax(0)
  }
  return(mt)
}
```
````

![image](https://github.com/r-lib/lintr/assets/39594914/85d648e8-0d23-4e68-9877-bae9875349c5)

**Comment by MichaelChirico** [comment]
`object_usage_linter()` only works on the body of functions so this that's why the first instance doesn't lint. You can try including `foo()`, i.e. a call to a function that's not defined, also outside the function to observe it also won't lint.

You can fix this by including `library(magrittr)` (or any other library that exports `%>%`) in your script; `library(tidyverse)` doesn't work.

**Comment by Aman9das** [comment]
Thanks!

**Comment by Aman9das** [comment]
I've fixed this issue by silentloading tidyverse in .RProfile
