### ISSUE TITLE
Return an empty list with `<lints>` class in addin

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/lintr#2556]
Instead of returning `return(list())`, we should be returning:

              A `list()` with class `"lints"` would be better (so that the print method is the correct one).

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/2418#discussion_r1554990377_

**Comment by MichaelChirico** [comment]
`return(list())` from a linter is not the same as `return(list())` from `addin_lint()`.

The former is consumed by `lint()`, which then runs `flatten_lints()` to apply the "lints" class before returning for printing/further handling.

The latter is not:

https://github.com/r-lib/lintr/blob/d86738f15ede8e16589f91424a2865134534069f/R/addins.R#L2-L12

The `return(lint())` here is an _alternative_ to the `lint()` output, which is always "lints"-classed. So we need to apply the "lints" class instead of just returning a plain `list()`.

Returning `list()` and letting `flatten_lints()` is probably much better from an efficiency point of view, so I don't think there's anything worth handling here -- I would just fix this in `addin_lint()`.

**Comment by IndrajeetPatil** [comment]
Thanks for the detailed explanation. I was indeed confused about this when I created the issue; it's clearer to me.
