### ISSUE TITLE
Bioconductor style linters

### ISSUE THREAD

**Issue by jimhester** [r-lib/lintr#43]
Add as an optional default perhaps?

http://bioconductor.org/developers/how-to/coding-style/

**Comment by mjsteinbaugh** [comment]
@jimhester Any update on this? Would love to see this feature added. I'd be happy to help contribute.

**Comment by kjohnsen** [comment]
I'd also be interested in this

**Comment by jimhester** [comment]
For those interested I would gladly review a PR!

**Comment by kjohnsen** [comment]
I could use this since I'm developing a Bioconductor package now, so I'll see what I can do to help

**Comment by jimhester** [comment]
https://bioconductor.org/developers/how-to/coding-style/ would probably be a useful place to start.

**Comment by mjsteinbaugh** [comment]
@llrs I've been using this [.lintr file](https://github.com/steinbaugh/basejump/blob/master/.lintr) in my packages, which has some additional checks

**Comment by russHyde** [comment]
Hi @mjsteinbaugh , would you be OK if I used your .lintr for basejump to define a list of bioconductor defaults within lintr?

**Comment by mjsteinbaugh** [comment]
Sure thing!

**Comment by russHyde** [comment]
There's some additional best-practices mentioned here:
http://bioconductor.org/developers/package-guidelines/#rcode

- Use vapply() instead of sapply() and use the various apply functions instead of for loops.
- Use seq_len() or seq_along() instead of 1:...
 -Use TRUE/FALSE instead of T/F
- Avoid class()== and class()!= instead use is()
- Use system2() instead of system
- Do not use set.seed in any internal R code.
- No browser() calls should be in code
- Avoid the use of <<-.
- Avoid use of direct slot access with @ or slot(). Accessor methods should be created and utilized
- Use <- instead of = for assignment
- Function names should be camel case or utilize the underscore _ and not have a dot . which indicates S3 dispatch.
- Use dev.new() to start a graphics drive if necessary. Avoid using x11() or X11() for it can only be called on machines that have access to an X server.

**Comment by mjsteinbaugh** [comment]
Yes refer to `BiocCheck::BiocCheck()` for details on some additional Bioconductor checks. In particular, I run it on CI with these flags: https://github.com/acidgenomics/Rcheck/blob/master/checks/bioc-check

**Comment by mjsteinbaugh** [comment]
Also, one addition that would be particularly useful in my opinion is improved handling of internal S4 method functions, which currently return as lint errors. Here's an example:
https://github.com/acidgenomics/basejump/blob/master/R/counts-methods.R#L46

`counts,SummarizedExperiment` will currently fail the `camelCase` lint check. This is similar S3 method lint issue reported in #223.

**Comment by MichaelChirico** [comment]
Encourage anyone that's interested to file PRs. Would especially be nice to include some for the 3.0.0 release. A lot of the points referenced in https://github.com/r-lib/lintr/issues/43#issuecomment-552857792 are already doable with existing linters; others would be straightforward adaptations of existing logic (see e.g. the linters filed in #884). We can add the `bioconductor` tag to allow `linters_with_tags("bioconductor")` to facilitate easy `.lintr` configs.

**Comment by MichaelChirico** [comment]
Gonna close this issue so it's not just indefinitely open. We remain open to PRs, but none of the current maintainers are too familiar with BioConductor practices. Moving forward interested contributors might consider:

 - Filing individual PRs for supporting linters not yet available in {lintr}. If you know a particular rule you'd like to see, but are intimidated about getting started writing a new linter, please reach out & we are happy to help.
 - File feature requests for extending/parameterizing existing linters to support different styles.
 - File a new master issue listing out specific rules to support. The current issue has too much other discussion -- starting a new, focused issue with tangible end points would be more helpful.
