### ISSUE TITLE
sprintf_linter not working on edge cases

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/lintr#626]
In the following cases, `sprintf_linter` might not work properly:

1. `...` is used in the argument (https://github.com/jimhester/lintr/pull/625#issuecomment-735397084):

```r
f <- function(id, ...) {
  sprintf("%d %d, %d", id, ...) ### too few arguments
}
```

2. Supplying arguments in non-typical order (https://github.com/jimhester/lintr/pull/625#issuecomment-735398166):

```r
f(42, fmt = "bla")
```

These cases might be not worth fixing as they are quite far from standard usage.

**Comment by AshesITR** [comment]
2. could be worth for `sprintf` directly by checking if any of the argument names are `fmt`, `fm`, or `f` - moving the first match to the front if that is the case.

Example code:

`sprintf(1, f = "%d")`
`sprintf(1, 2, fm = "%d %d")`
`sprintf(1, 2, 3, fmt = "%d %d %d")`

**Comment by MichaelChirico** [comment]
Don't think we should encourage partial matching 😉

the dots case should be easy enough to handle, I'm not sure if it's worth
handling the fmt= case

**Comment by AshesITR** [comment]
Since we have to examine the call structure to find `...` anyway, I'd go for it and at least support reordering of the fully specified argument, `fmt`. Especially since it's found in the wild.

I can also imagine this being useful in pipe situations where you do some computation and then pretty-print the result (e.g. `x %>% compute_something() %>% sprintf(fmt = "%.15f")`)

**Comment by MichaelChirico** [comment]
I would say in a sense the issue here is much more general -- in fact none of the xpath-based linters (to my knowledge) do any sort of `match.call` logic. It might be worth implementing some helper to achieve that... but I think it's not super important to do before release.
