### ISSUE TITLE
Make R/ conform to `cyclocomp_linter`

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#653]
Final part of #584.

The current target is to use `cyclocomp_linter(15)`. It's currently enabled at `cyclocomp_linter(29)`.

At current `master`, We get the following functions triggering the `cyclocomp_linter`:

 - [ ] CC=17 R/closed_curly_linter.R:6:1:closed_curly_linter
 - [ ] CC=16 R/commas_linter.R:5:1:commas_linter
 - [ ] CC=16 R/get_source_expressions.R:340:1:fix_tab_indentations
 - [ ] CC=18 R/get_source_expressions.R:393:1:fix_eq_assigns
 - [ ] CC=29 R/lint.R:25:1:lint
 - [ ] CC=18 R/namespace_linter.R:9:1:namespace_linter
 - [ ] CC=16 R/open_curly_linter.R:4:1:open_curly_linter
 - [ ] CC=17 R/path_linters.R:104:1:split_path
 - [ ] CC=19 R/sprintf_linter.R:4:1:sprintf_linter

Because each of these is more than a whitespace change/trivial refactor, each function should be addressed in its own PR.

PS One worry I have is that this one is more likely to be a high barrier for contributed PRs, as the linter's advice is not particularly actionable (my cyclomatic complexity is 16... OK... what exactly do I do now?). For the vast majority of people contributing PRs, any bot pestering them about the "cyclomatic complexity" of their PR is going to be confusing to say the least. Do we really want to send contributors on a chase to figure out what cyclomatic complexity is, and then how to apply it to their code?

One alternative would be to keep the threshold much lower during dev (say 29, like currently), and then have a pre-release task to address cyclomatic complexity among the maintainers before release.

Any thoughts?

**Comment by AshesITR** [comment]
Do you think the error message of cyclocomp could be made more self-contained by including actionable advice?
Something like "try reducing the number of code branches by factoring out logic into separate, smaller functions"?

Otherwise it seems we'd have to continuously up / down the cyclocomp config...
Maybe we should discuss increasing the threshold of 15 in general. NB the factory default for cyclocomp is 25 which would make a lot of the current lints disappear.

**Comment by MichaelChirico** [comment]
Closing in favor of #1186
