### ISSUE TITLE
Change deprecation warnings for version 2.0.1.9001 to version 3.0.0

### ISSUE THREAD

**Issue by AshesITR** [r-lib/lintr#835]

**Comment by MichaelChirico** [comment]
Changed the task in #824 to just be the title of this issue, and closing this one.

The thinking is, that update should be done with very precise "timing". Ideally no one sees `3.0.0` as the deprecated version while the DESCRIPTION version is <3.0.0. But 3.0.0 in the DESCRIPTION should be released to CRAN before GitHub.

In my experience that means keeping a release branch that's not merged to master until any back-and-forth with CRAN is complete and 3.0.0 actually hits CRAN servers.

To me, then, it makes more sense to track this issue as a bullet within the release issue alone, since this one won't be closed by a PR to `master`, only by a commit to the release branch.

Happy to re-open if I'm misunderstanding.

**Comment by AshesITR** [comment]
As discussed, I've updated #836 to  include `usethis::use_version("major")`.
